### ISSUE TITLE
How can I use my GPU? when I launch it, it  says in the CMD that GPU is not available, so it usedCPU.

### ISSUE THREAD

**Issue by FemBoxbrawl** [Vali-98/XTTS-RVC-UI#5]

**Comment by Vali-98** [comment]
Hey there, if you have a CUDA compatible nvidia GPU it should be done automatically since its just using torch. 

If you have an AMD / Intel GPU, this won't be possible.

Please reopen the issue if you are using nvidia.

**Comment by FemBoxbrawl** [comment]
> Hey there, if you have a CUDA compatible nvidia GPU it should be done automatically since its just using torch.
> 
> If you have an AMD / Intel GPU, this won't be possible.
> 
> Please reopen the issue if you are using nvidia.

I got it to work,  I had to use this command: to get the right version and then it worked:

pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118


and last question, do the audios save automatically? or no?

**Comment by Vali-98** [comment]
> and last question, do the audios save automatically? or no?

It simply outputs the latest generations to the output.wav and outputrvc.wav in the root folder which replaces previous generations. If you want to save it, you can download it from the gradio UI download button or copy paste it manually.
